### ISSUE TITLE
June Meetup Plan: Kotlin KMM

### ISSUE THREAD

**Issue by abhishekmishragithub** [gdgchennai/handbook#1]
Speakers: Somu and Sangeet 
Date: June 30 Friday 
Venue: 
Target: Intermediate Android Devs
Content: https://docs.google.com/document/d/10KDE9ifimi0ivmhYBi78mMaTmeHC8LIHy-aHNgtreC8/edit?usp=sharing

**Comment by navhits** [comment]
Closing since event is over
