### ISSUE TITLE
KCD Document

### ISSUE THREAD

**Issue by Ram1103** [gdgchennai/handbook#2]
Read through the necessary details given in the mail @abhishekmishragithub ,  will be updating in the docs 

DOCS : [DOC](https://docs.google.com/document/d/1Ymqh5oUvaEphZFWbC2tVOtHeqA7YLnnHUU9odImkiDY/edit?usp=sharing)

@abhishekmishragithub @msomu  need your public phone numbers

**Comment by navhits** [comment]
Closing since event is over
