### ISSUE TITLE
KMM August Event - 1

### ISSUE THREAD

**Issue by Ram1103** [gdgchennai/handbook#4]
**Event plan:** 

- Link : https://lu.ma/gdgchennai-august-2023

- Event : Jetpack Compose, Dev Mode & Relay • GDG Chennai August 2023 Event
​Talks
Working with Jetpack Compose & Kotlin by Somasundaram Mahesh
Introduction to Figma's new Dev Mode with Jetpack Compose by Sandeep Baskaran
Figma + Relay demo by Somasundaram Mahesh

- Agenda
11.00 PM to 11.30 AM - Check-in
11.30 AM to 1.00 PM - Jetpack Compose
1.00 PM to 2.00 PM - Lunch
2.00 PM to 2.30PM - Dev Mode and Relay Demo
2.30 to 3.30 PM - Networking

- Prerequisites
• Experience working on Android projects
• Basic understanding of Jetpack Compose and Kotlin
• Familiarity with composables and state management
• Basic layout building is good to have

- Speakers:
• Somasundram M
• Trishi Raj

- Volunteers 
•  Ram
• Karan
• Sanju

**Comment by Ram1103** [comment]
**Things to keep in mind for next event in the form:**
- Ask gender
- Year if student 
- professional instead of developer

**Comment by navhits** [comment]
Closing this since the event is over
